<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Try_catch문</title>
</head>
<body>
    <script>
        /* 예외처리 없이 사용한다면 아래에 실행이 되지 않음. 이미 앞이 에러가 터져서 멈춤.
        const result = new Array(-1);
        console.log('1111');
        */

        // try와 catch를 같이 사용해야함. try 안에는 에러가 터질만한 애가 들어가야함. 에러가 터지는 애 아래에 bbb는 실행이 되지 않기 때문에.
        // 밖으로 빼 줘야한ㄴ다.
        try {
            console.log('AAAA');
            const result = new Array(-1);   // 에러객체가 e에 들어감.
            console.log('BBBB');
        } catch (e) {
            console.error('catch : ' + e.name);   // 실행됨!!
        }
        console.log('BBBB');
        console.log('1111');

        console.log(`(1) try_catch 끝`);
        
        console.log('---------------------');

        try {           // 예외가 실행되지 않았기 때문에 try가 실행된 후 catch는 실행이 안되고 빠져나와서 밑에 실행.
            console.log('AAAA');
            console.log('BBBB');
            console.log('CCCC');
        } catch (e) {
            console.error(e.name); // 실행 안됨.
        }
        
        console.log(`(2) try_catch 끝`);
        console.log('---------------------');
        
        try {
            console.log('AAAA');
            const result = new Array(-1);
            console.log('BBBB');
        } catch (e) {
            console.error(e.name); // 실행됨.
        } finally {     // try, catch는 필수, finally는 옵션. 무조건 실행이 됨.
            console.log('무조건 실행됨!')
        }

        console.log(`(3) try_catch 끝`);

        // finally와 밖의 콘솔의 차이점. 함수에서 차이가 남.
        /*
            3번예시까지는 표시나지 않음.
        */

        console.log('---------------------');
    </script>
</body>
</html>